/* =====================================================================
   PRODUCT CATALOGUE — the single source of truth.
   Schema is CMS-ready and stable: identity and numbers are language-neutral
   and sortable, all prose lives under `copy[locale]`, and media is addressed
   by key rather than by URL so a CMS can swap the asset without touching copy.
   The same object is exported as catalog.json for the Dev team.

   Granularity note: a "product" here is a SKU, not a flavour family. Tsingtao
   sells the same lager in a 330 bottle, a 640 bottle and a 500 can, and each
   one is a real product with its own occasion, its own pour and its own copy.
   Anything shared between them (the 1903 formula, the Laoshan water) is stated
   once per record rather than inherited, so no edit here can contradict another.

   Each record carries two editorial fields on top of the specification:
     legacy — a pull-quote line, the one sentence a visitor should remember
     award  — third-party recognition, where it genuinely exists
   The specification numbers are never restated in the prose: they are rendered
   from `specs` so a copy edit can never contradict a spec edit.
   ===================================================================== */
const CATALOG = {
  schema_version: '1.3',
  brand: { id:'vertex', wordmark:'BREWER', kicker:'TSINGTAO', origin:'Qingdao, China', founded:1903 },
  locales: ['vi','en','zh'],
  default_locale: 'vi',
  products: [

  /* ---------------------------------------------------------------- 1 */
  {
    id:'tsg-lager-330', slug:'premium-lager-330-bottle', sku:'TSG-LGR-330B',
    line:{vi:'Dòng Truyền Thống', en:'The Heritage Line', zh:'经典系列'},
    category:'lager', order:1, featured:true, ring:'plain', ringCaption:'Premium 330',
    media:{ tile:'144', gallery:['144','105','167'] },
    specs:{
      abv:4.7,
      formats:[{kind:'bottle', volume_ml:330}],
      ingredients:{vi:'Nước tinh khiết, mạch nha lúa mạch, hoa bia, men bia',
                   en:'Purified water, barley malt, hops, yeast',
                   zh:'纯净水、大麦麦芽、啤酒花、酵母'},
      fermentation:null, energy_kcal_100ml:null, sugar_free:false
    },
    copy:{
      vi:{ name:'Bia Chai Tsingtao Premium 330ml',
           tagline:'Chai nhỏ, công thức nguyên bản — đủ trọn cho một buổi tối.',
           badge:'CHAI 330ML',
           legacy:'Một chai 330 ml. Đủ cho một người, đủ lâu cho một câu chuyện.',
           description:'Đây là chai xanh 330 ml quen thuộc nhất của Tsingtao tại Việt Nam. Kích thước vừa để uống từ tối tới khuya mà không phải tính toán, vừa đủ lớn để lớp bọt vẫn đứng được trên miệng chai thay vì lún xuống ngay.\n\nBên trong là công thức ủ bia truyền thống chuẩn Đức từ năm 1903, ủ lạnh và chín ổn định suốt 12 tháng trước khi đóng chai. Vị đắng nhẹ, hậu vị sạch và cân bằng — thứ vị có thể uống liên tục mà không bao giờ thấy nặng.',
           features:['Chai 330 ml gọn nhẹ, dễ mang đi và bảo quân lạnh suốt buổi.',
                     'Cùng công thức lager truyền thống với chai lớn — không rút ngắn bất kỳ khâu nào.',
                     'Vị đắng nhẹ, cân bằng, dễ uống ngay cả khi trời nóng.'],
           pairing:['Một buổi tối riêng','Ăn vặt đêm','Nhâm nhi cùng bạn'],
           award:{vi:'Huy chương Vàng World Beer Championship · European Beer Star',
                  en:'World Beer Championship Gold Medal · European Beer Star',
                  zh:'世界啤酒锦标赛金奖 · 欧洲啤酒之星'},
           cta:'Đặt chai 330ml' },
      en:{ name:'Tsingtao Premium Lager 330ml Bottle',
           tagline:'The small bottle, the unchanged recipe — one whole evening in it.',
           badge:'330ML BOTTLE',
           legacy:'One 330 ml bottle. Enough for one person, long enough for a story.',
           description:'This is the familiar 330 ml green bottle of Tsingtao in Vietnam. Small enough to drink from dinner to late without counting, large enough that the head still stands on the mouth of the bottle instead of collapsing at once.\n\nInside is the German brewing formula of 1903, cold-conditioned and matured for twelve months before it is filled. Light bitterness, a clean balanced finish — a taste you can keep drinking without ever finding it heavy.',
           features:['A 330 ml bottle: light to carry, easy to keep cold on the move.',
                     'The same traditional lager formula as the larger bottle, with no step shortened.',
                     'Light, balanced bitterness that stays drinkable on a hot day.'],
           pairing:['An evening on its own','Late-night snacks','Nibbling with friends'],
           award:{en:'World Beer Championship Gold Medal · European Beer Star',
                  vi:'Huy chương Vàng World Beer Championship · European Beer Star',
                  zh:'世界啤酒锦标赛金奖 · 欧洲啤酒之星'},
           cta:'Order the 330ml' },
      zh:{ name:'青岛啤酒 经典拉格 330毫升',
           tagline:'小瓶身，原配方——足够撑起一个晚上。',
           badge:'330毫升玻璃瓶',
           legacy:'一支 330 毫升。为一个人足量，为一个故事够久。',
           description:'这是青岛啤酒在越南最熟悉的一支绿瓶 330 毫升。体积刚好，喝到深夜也不必计算；又足够大，让泡沫仍能挺立在瓶口，而不是一开盖就塌下去。\n\n瓶中是 1903 年的德国传统酿造配方，灌装前经过 12 个月冷链熟成。苦味柔和，收尾干净平衡——一种可以一直喝下去、从不觉得厚重的味道。',
           features:['330 毫升瓶身，轻便易携，便于全程保持冰凉。',
                     '与大瓶完全相同的传统拉格配方，没有任何一道工序被缩短。',
                     '苦味柔和平衡，天气炎热时同样适合饮用。'],
           pairing:['独享的夜晚','夜宵','与朋友小酌'],
           award:{zh:'世界啤酒锦标赛金奖 · 欧洲啤酒之星',
                  en:'World Beer Championship Gold Medal · European Beer Star',
                  vi:'Huy chương Vàng World Beer Championship · European Beer Star'},
           cta:'选购 330 毫升' }
    }
  },

  /* ---------------------------------------------------------------- 2 */
  {
    id:'tsg-lager-640', slug:'premium-lager-640-bottle', sku:'TSG-LGR-640B',
    line:{vi:'Dòng Truyền Thống', en:'The Heritage Line', zh:'经典系列'},
    category:'lager', order:2, featured:true, ring:'plain', ringCaption:'Premium 640',
    media:{ tile:'105', gallery:['105','167'] },
    specs:{
      abv:4.7,
      formats:[{kind:'bottle', volume_ml:640}],
      ingredients:{vi:'Nước tinh khiết, mạch nha lúa mạch, hoa bia, men bia',
                   en:'Purified water, barley malt, hops, yeast',
                   zh:'纯净水、大麦麦芽、啤酒花、酵母'},
      fermentation:null, energy_kcal_100ml:null, sugar_free:false
    },
    copy:{
      vi:{ name:'Bia Chai Tsingtao Premium 640ml',
           tagline:'Nửa lít trong một chai — vì đôi khi hai người giải quyết chuyện đó nhanh hơn.',
           badge:'CHAI 640ML',
           legacy:'Hai chai 330 ml. Một chai 640 ml. Không phải hai lần rót.',
           description:'Hai người và một đêm, chai 640 ml xử lý gọn hơn. Nó vẫn là cùng công thức lager từ năm 1903, cùng độ lạnh 12 tháng, cùng nước suối dưới chân núi Lao Sơn — chỉ khác ở chỗ bạn không phải rót hai lần.\n\nVai chai được nổi núm theo kiểu cổ điển, và đó không phải chi tiết trang trí: nó giữ cho lớp bọt dày và hương thơm bị giữ lại lâu hơn trong quá trình rót. Hình dáng chai cũng cho bạn một lý do rất hợp lý để không vội vàng.',
           features:['Chai 640 ml — dung tích chuẩn cho hai người, tiết kiệm hơn hai chai nhỏ.',
                     'Vai chai nổi núm giữ bọt và hương thơm lâu hơn khi rót.',
                     'Cùng công thức và độ chín 12 tháng với toàn bộ dòng lager.'],
           pairing:['Chia nhẹ bữa tiệc','Ăn cùng món hải sản nướng','Bữa cơm gia đình'],
           award:{vi:'Cùng công thức với dòng lager truyền thống',
                  en:'The same formula as the heritage lager range',
                  zh:'与经典拉格系列同配方'},
           cta:'Đặt chai 640ml' },
      en:{ name:'Tsingtao Premium Lager 640ml Bottle',
           tagline:'Half a litre in one bottle — because sometimes two people settle it faster.',
           badge:'640ML BOTTLE',
           legacy:'Two 330s. One 640. Not two pours.',
           description:'Two people, one evening, and a 640 ml bottle handles it more neatly. It is still the same 1903 lager formula, the same twelve months of cold conditioning, the same spring water from the foot of Mount Laoshan — the only difference is that you pour once.\n\nThe shoulder carries a traditional embossed crown, and that is not decoration: it holds the head thicker and keeps the aroma in the glass longer as you pour. The shape also gives you a perfectly reasonable excuse not to rush.',
           features:['A 640 ml bottle — the sensible size for two, and less fuss than two small ones.',
                     'The embossed shoulder keeps the head and the aroma in the glass for longer.',
                     'The same formula and twelve-month conditioning as the whole lager range.'],
           pairing:['Easy sharing at a gathering','Grilled seafood','A family meal'],
           award:{en:'The same formula as the heritage lager range',
                  vi:'Cùng công thức với dòng lager truyền thống',
                  zh:'与经典拉格系列同配方'},
           cta:'Order the 640ml' },
      zh:{ name:'青岛啤酒 经典拉格 640毫升',
           tagline:'一瓶半升——有时两个人解决这件事比倒两次更快。',
           badge:'640毫升玻璃瓶',
           legacy:'两支 330，一支 640。少倒一次。',
           description:'两个人，一个晚上，640 毫升瓶装处理得更从容。它依然是 1903 年的拉格配方，同样 12 个月冷链熟成，同样取自崂山山泉——唯一的区别是你只需倒一次。\n\n瓶肩保留了传统的压模皇冠瓶盖，这不是装饰：它能让泡沫更厚实，也能在倒酒时把香气在杯中留得更久。而瓶身的比例，也给了你一个完全站得住脚的理由——不着急。',
           features:['640 毫升瓶身，两人分享的合宜容量，比两支小瓶更省事。',
                     '瓶肩压模设计，倒酒时让泡沫与香气在杯中停留更久。',
                     '与整个拉格系列相同的配方与 12 个月熟成工艺。'],
           pairing:['聚会分享','烤制海鲜','家庭聚餐'],
           award:{zh:'与经典拉格系列同配方',
                  en:'The same formula as the heritage lager range',
                  vi:'Cùng công thức với dòng lager truyền thống'},
           cta:'选购 640 毫升' }
    }
  },

  /* ---------------------------------------------------------------- 3 */
  {
    id:'tsg-lager-500', slug:'premium-lager-500-can', sku:'TSG-LGR-500C',
    line:{vi:'Dòng Truyền Thống', en:'The Heritage Line', zh:'经典系列'},
    category:'lager', order:3, featured:true, ring:'pay', ringCaption:'Premium 500',
    media:{ tile:'9206', gallery:['9206','113'] },
    specs:{
      abv:4.7,
      formats:[{kind:'can', volume_ml:500}],
      ingredients:{vi:'Nước tinh khiết, mạch nha lúa mạch, hoa bia, men bia',
                   en:'Purified water, barley malt, hops, yeast',
                   zh:'纯净水、大麦麦芽、啤酒花、酵母'},
      fermentation:null, energy_kcal_100ml:null, sugar_free:false
    },
    copy:{
      vi:{ name:'Bia Lon Tsingtao Premium 500ml',
           tagline:'Lon tiêu chuẩn của nhà máy — lạnh, gọn, và sẵn sàng ngay.',
           badge:'LON 500ML',
           legacy:'Lon 500 ml. Dung tích lớn nhất trong dòng lager thường.',
           description:'Đây là lon 500 ml — định dạng mà nhà máy tin dùng nhất và cũng là lon lớn nhất trong dòng lager thường. Nó khác chai ở đúng một điểm quan trọng: giữ nhiệt tốt hơn, mở ra vẫn lạnh ngay cả sau một lúc đi ngoài.\n\nVị thì y hệt. Cùng công thức ủ bia truyền thống chuẩn Đức từ 1903, cùng độ chín lạnh 12 tháng, cùng ba nguyên liệu cốt lõi. Nhấc lon lạnh, đậy nắp, kéo — xong.',
           features:['Lon 500 ml giữ nhiệt tốt nhất trong ba định dạng, uống ở đâu cũng còn lạnh.',
                     'Vị hoàn toàn giống dòng chai 330 ml và 640 ml.',
                     'Vỏ lon tái chế, nhẹ hơn thủy tinh và dễ vận chuyển xa.'],
           pairing:['Tiệc có đông người','Nhâm nhi cùng đồ ăn vặt','Dựng cuối ngày làm việc'],
           award:{vi:'Lon 500 ml — định dạng phổ biến nhất',
                  en:'The 500 ml can — the most widely served format',
                  zh:'500毫升易拉罐——最常见的规格'},
           cta:'Đặt lon 500ml' },
      en:{ name:'Tsingtao Premium Lager 500ml Can',
           tagline:'The brewery’s standard can — cold, compact, and ready.',
           badge:'500ML CAN',
           legacy:'The 500 ml can. The largest format in the standard lager range.',
           description:'This is the 500 ml can — the format the brewery relies on most, and the largest can in the standard lager range. It differs from the bottles in exactly the way that matters: it holds its cold far better, and opens cold even after a while out and about.\n\nThe taste is identical. The same German brewing formula of 1903, the same twelve months of cold conditioning, the same three core ingredients. Pick it up cold, pull the tab, and it is done.',
           features:['The 500 ml can holds its cold best of the three formats, wherever you open it.',
                     'The taste is exactly that of the 330 ml and 640 ml bottles.',
                     'A recyclable aluminium shell: lighter than glass and far easier to move.'],
           pairing:['A busy table','Snacks and small plates','The end of a working day'],
           award:{en:'The 500 ml can — the most widely served format',
                  vi:'Lon 500 ml — định dạng phổ biến nhất',
                  zh:'500毫升易拉罐——最常见的规格'},
           cta:'Order the 500ml' },
      zh:{ name:'青岛啤酒 经典拉格 500毫升',
           tagline:'酒厂的标准罐——冰凉、紧凑、随时开喝。',
           badge:'500毫升易拉罐',
           legacy:'500 毫升。经典拉格系列中最大的规格。',
           description:'这是 500 毫升易拉罐——酒厂最倚重的规格，也是常规拉格系列中容量最大的罐装。它与瓶装的差别恰好落在最要紧的一点：保冷性更好，即便带着出门一阵子，拉环拉开时依然是凉的。\n\n味道完全一致。同样的 1903 年德国传统配方，同样 12 个月冷链熟成，同样三样核心原料。拿起来，拉环，一气呵成。',
           features:['500 毫升罐在三种规格中保冷性最佳，随时随地打开都是冰凉的。',
                     '风味与 330 毫升、640 毫升瓶装完全相同。',
                     '铝罐可回收，比玻璃更轻，也更便于远途运输。'],
           pairing:['热闹的餐桌','小食与下酒菜','一天的收尾'],
           award:{zh:'500毫升易拉罐——最常见的规格',
                  en:'The 500 ml can — the most widely served format',
                  vi:'Lon 500 ml — định dạng phổ biến nhất'},
           cta:'选购 500 毫升' }
    }
  },

  /* ---------------------------------------------------------------- 4 */
  {
    id:'tsg-1903-premium', slug:'1903-premium', sku:'TSG-PRM-500',
    line:{vi:'Dòng Thượng Hạng', en:'The Reserve Line', zh:'尊享系列'},
    category:'lager', order:4, featured:true, ring:'plain', ringCaption:'1903 Reserve',
    media:{ tile:'152', gallery:['152','052'] },
    specs:{
      abv:5.0,
      formats:[{kind:'can', volume_ml:500}],
      ingredients:{vi:'Nước tinh khiết, mạch nha lúa mạch, hoa bia, men bia',
                   en:'Purified water, barley malt, hops, yeast',
                   zh:'纯净水、大麦麦芽、啤酒花、酵母'},
      fermentation:{vi:'Lên men kép (Double Fermentation)',
                    en:'Double fermentation',
                    zh:'双酵母发酵'},
      energy_kcal_100ml:null, sugar_free:false
    },
    copy:{
      vi:{ name:'Bia Tsingtao 1903 Premium 500ml',
           tagline:'Tinh hoa chắt lọc dành cho người sành bia.',
           badge:'LÊN MEN KÉP',
           legacy:'Đọc lại mẻ bia đầu tiên. Năm 1903.',
           description:'Phiên bản đặc biệt được tạo ra để tôn vinh mẻ bia đầu tiên ra đời năm 1903 — thời khắc Tsingtao chính thức bước vào thế giới. Đây không phải một dòng bia mới, mà là cách nhà máy kể lại khoảnh khắc khởi đầu của chính mình.\n\nQuy trình lên men kép độc quyền kéo dài lâu hơn thông thường, giúp vị bia đậm đà và sánh mịn hơn, bền hơn trên lưỡi. Hương thơm mạch nha caramel bùng nổ ngay từ ngụm đầu tiên, kéo dài đến hậu vị khô và sâu, nơi hương gỗ và caramel cùng đọng lại.',
           features:['Hàm lượng mạch nha cao hơn mang lại màu vàng hổ phách óng ánh và cấu trúc vị sâu lắng.',
                     'Lên men kép độc quyền: thời gian ủ dài hơn, vị đậm và bền hơn.',
                     'Thiết kế lon vàng xanh đậm phối hoa văn mạ vàng, khẳng định đẳng cấp người thưởng thức.'],
           pairing:['Thịt đỏ','Bít tết','Các món hầm đậm vị'],
           award:{vi:'Rượu bia dành cho người hiểu và tôn trọng quy trình',
                  en:'A beer for drinkers who respect the process',
                  zh:'为懂工艺、敬重流程的饮者而酿'},
           cta:'Trải nghiệm đẳng cấp 1903' },
      en:{ name:'Tsingtao 1903 Premium Lager 500ml',
           tagline:'The distilled essence, reserved for the discerning drinker.',
           badge:'DOUBLE FERMENTED',
           legacy:'A return to the first brew. 1903.',
           description:'A limited expression created to honour the first brew of 1903 — the moment Tsingtao entered the world. This is not a new line of beer; it is how the brewery retells its own beginning.\n\nA proprietary extended double-fermentation process gives a fuller, silkier beer that holds longer on the palate. Caramel-malt aroma arrives on the very first sip and carries through to a dry, deep finish where notes of wood and caramel settle together.',
           features:['Elevated wort strength delivers luminous amber colour and a layered, structured palate.',
                     'Proprietary double fermentation: a longer, slower build for a fuller, longer finish.',
                     'A deep gold and green can finished in gold, designed to signal the drinker’s standing.'],
           pairing:['Red meat','Steak','Slow braises'],
           award:{en:'A beer for drinkers who respect the process',
                  vi:'Rượu bia dành cho người hiểu và tôn trọng quy trình',
                  zh:'为懂工艺、敬重流程的饮者而酿'},
           cta:'Experience the 1903 Reserve' },
      zh:{ name:'青岛啤酒 1903 尊享 500毫升',
           tagline:'为懂酒之人精心酿造的精华之作。',
           badge:'双酵母发酵',
           legacy:'重回第一缸佳酿。1903 年。',
           description:'为致敬 1903 年首缸佳酿而推出的特别版本——那是青岛正式走向世界的时刻。这不是一条全新的产品线，而是酒厂对自身起点的一次复述。\n\n专有的延长双酵母发酵工艺带来更饱满、更丝滑的酒体，在口腔中停留更久。自第一口便释放焦糖麦芽香气，并一路延伸至干爽深邃的回味，尾韵中木质与焦糖层层交织。',
           features:['更高麦芽浓度带来澄澈琥珀色泽与层次分明的口感结构。',
                     '专有双酵母发酵：更长的熟成时间，更饱满、更耐久的余韵。',
                     '深金与墨绿罐体，饰以烫金纹样，彰显饮用者的品位与身份。'],
           pairing:['红肉','牛排','浓味炖菜'],
           award:{zh:'为懂工艺、敬重流程的饮者而酿',
                  en:'A beer for drinkers who respect the process',
                  vi:'Rượu bia dành cho người hiểu và tôn trọng quy trình'},
           cta:'体验 1903 尊享' }
    }
  },

  /* ---------------------------------------------------------------- 5 */
  {
    id:'tsg-zero-can', slug:'zero-alcohol-can', sku:'TSG-ZER-330C',
    line:{vi:'Dòng Không Độ', en:'The Zero Range', zh:'无醇系列'},
    category:'zero', order:5, featured:true, ring:'off', ringCaption:'Zero Can',
    media:{ tile:'129', gallery:['129','136'] },
    specs:{
      abv:0.0,
      formats:[{kind:'can', volume_ml:330}],
      ingredients:{vi:'Nước, mạch nha lúa mạch, hoa bia, men bia, chất điều chỉnh độ chua',
                   en:'Water, barley malt, hops, yeast, acidity regulators',
                   zh:'水、大麦麦芽、啤酒花、酵母、酸度调节剂'},
      fermentation:null, energy_kcal_100ml:null, sugar_free:false, low_calorie:true
    },
    copy:{
      vi:{ name:'Bia Lon Tsingtao Không Độ 330ml',
           tagline:'Trọn vị bia nguyên bản — hoàn toàn không cồn.',
           badge:'0.0% · ÍT CALO',
           legacy:'Sạch như nước. Đậm như bia.',
           description:'Đây là câu trả lời cho một câu hỏi đơn giản: có thể vừa giữ trọn hương vị bia, vừa tỉnh táo tuyệt đối? Công nghệ lọc cồn hiện đại của nhà máy loại bỏ cồn một cách chọn lọc, thay vì làm biến đổi cấu trúc bia.\n\nKết quả là một sản phẩm vẫn giữ nguyên hương thơm, độ sánh và hậu vị của dòng lager truyền thống. Ít calo, không cồn, và dễ dàng trở thành lựa chọn mặc định cho những khoảnh khắc cần sự tỉnh táo.',
           features:['Công nghệ lọc cồn tiên tiến giữ trọn dưỡng chất và vị bia tươi mát.',
                     '0.0% cồn, hàm lượng calo thấp — an toàn tuyệt đối khi lái xe, làm việc văn phòng hoặc trong các buổi giao tiếp thể thao.',
                     'Vỏ lon nhẹ, dễ bảo quản lạnh và dễ mang đi hơn chai thủy tinh.'],
           pairing:['Lái xe','Văn phòng','Buổi giao tiếp thể thao'],
           award:{vi:'Công nghệ lọc cồn đạt chứng nhận tại Đức',
                  en:'De-alcoholisation technology certified in Germany',
                  zh:'脱醇工艺技术获德国认证'},
           cta:'Sảng khoái không giới hạn' },
      en:{ name:'Tsingtao Zero Alcohol Lager 330ml Can',
           tagline:'All of the lager character, with none of the alcohol.',
           badge:'0.0% · LOW CAL',
           legacy:'Clean as water. Full as beer.',
           description:'This is the answer to a simple question: can you keep the taste of beer and stay completely clear? The brewery’s modern de-alcoholisation technology removes the alcohol selectively, rather than dismantling the structure of the beer.\n\nWhat is left carries the aroma, body and finish of the traditional lager range. Low in calories, free of alcohol, and an easy default for every occasion that calls for clarity.',
           features:['Advanced de-alcoholisation technology retains the nutritional value and refreshment of real beer.',
                     '0.0% alcohol and low in calories — completely safe for driving, the office, and sporting occasions.',
                     'A light can: easier to keep cold and easier to carry than glass.'],
           pairing:['Driving','The office','Sporting occasions'],
           award:{en:'De-alcoholisation technology certified in Germany',
                  vi:'Công nghệ lọc cồn đạt chứng nhận tại Đức',
                  zh:'脱醇工艺技术获德国认证'},
           cta:'Refreshment without limits' },
      zh:{ name:'青岛啤酒 无醇 330毫升',
           tagline:'完整的拉格风味，全程无酒精。',
           badge:'0.0% · 低热量',
           legacy:'清澈如水，饱满如啤。',
           description:'这是对一个简单问题的回答：能否既保留啤酒风味，又保持绝对清醒？酒厂先进的脱醇技术以选择性的方式剥离酒精，而非破坏啤酒本身的结构。\n\n留下来的，是传统拉格系列完整的香气、酒体与回味。低热量、无酒精，在任何需要保持清醒的场合，它都可以成为默认选择。',
           features:['先进的脱醇技术，完整保留营养价值与啤酒的清爽口感。',
                     '酒精度 0.0%、低热量，驾车、办公及各类体育社交场合均可安心饮用。',
                     '罐装轻便，比玻璃更易保持冰凉，也更方便携带。'],
           pairing:['驾车','办公','体育社交'],
           award:{zh:'脱醇工艺技术获德国认证',
                  en:'De-alcoholisation technology certified in Germany',
                  vi:'Công nghệ lọc cồn đạt chứng nhận tại Đức'},
           cta:'畅爽无极限' }
    }
  },

  /* ---------------------------------------------------------------- 6 */
  {
    id:'tsg-zero-bottle', slug:'zero-alcohol-bottle', sku:'TSG-ZER-330B',
    line:{vi:'Dòng Không Độ', en:'The Zero Range', zh:'无醇系列'},
    category:'zero', order:6, featured:false, ring:'plain', ringCaption:'Zero Bottle',
    media:{ tile:'136', gallery:['136','129'] },
    specs:{
      abv:0.0,
      formats:[{kind:'bottle', volume_ml:330}],
      ingredients:{vi:'Nước, mạch nha lúa mạch, hoa bia, men bia, chất điều chỉnh độ chua',
                   en:'Water, barley malt, hops, yeast, acidity regulators',
                   zh:'水、大麦麦芽、啤酒花、酵母、酸度调节剂'},
      fermentation:null, energy_kcal_100ml:null, sugar_free:false, low_calorie:true
    },
    copy:{
      vi:{ name:'Bia Chai Tsingtao Không Độ 330ml',
           tagline:'Vị không cồn, trong cái vỏ chai quen thuộc.',
           badge:'0.0% · CHAI 330ML',
           legacy:'Không cồn, nhưng vẫn là một chai bia đúng nghĩa.',
           description:'Cùng dòng không cồn, nhưng đựng trong chai xanh 330 ml quen thuộc thay vì lon. Vị, độ sánh và hậu vị hoàn toàn giống — công nghệ lọc cồn áp dụng như nhau, chỉ khác lớp vỏ ngoài.\n\nVới nhiều người, hình thức vẫn là một phần của trải nghiệm. Chai giữ nhiệt chậm hơn lon một chút nhưng dễ rót hơn, và bạn có thể đặt nó cạnh những chai khác trên bàn mà không ai hỏi vì sao.',
           features:['Vị và công nghệ lọc cồn giống hệt dòng lon 330 ml.',
                     'Chai xanh 330 ml dễ rót, giữ nhiệt tốt hơn các loại nhựa thông thường.',
                     '0.0% cồn, ít calo — cùng đối tượng và cùng dịp như dòng lon.'],
           pairing:['Bữa cơm gia đình','Buổi tối không cần tỉnh','Nhâm nhi cùng bạn'],
           award:{vi:'Cùng dòng với lon Không Độ 330 ml',
                  en:'The same range as the Zero 330 ml can',
                  zh:'与无醇 330 毫升罐装同系列'},
           cta:'Đặt chai không độ' },
      en:{ name:'Tsingtao Zero Alcohol Lager 330ml Bottle',
           tagline:'The alcohol-free taste, in the bottle people already know.',
           badge:'0.0% · 330ML BOTTLE',
           legacy:'No alcohol, and still unmistakably a bottle of beer.',
           description:'The same zero-alcohol beer, in the familiar 330 ml green bottle rather than a can. The taste, the body and the finish are identical — the de-alcoholisation technology is applied exactly the same way; only the packaging differs.\n\nFor many people the form is part of the experience. A bottle holds its cold a little more steadily than a can, pours more cleanly, and you can set it down on the table beside the others without anyone asking why.',
           features:['Identical taste and de-alcoholisation technology to the Zero 330 ml can.',
                     'A 330 ml green bottle: cleaner to pour and steadier on temperature than plastic.',
                     '0.0% alcohol and low in calories — the same audience and the same occasions as the can.'],
           pairing:['A family meal','An evening that does not need to end early','Nibbling with friends'],
           award:{en:'The same range as the Zero 330 ml can',
                  vi:'Cùng dòng với lon Không Độ 330 ml',
                  zh:'与无醇 330 毫升罐装同系列'},
           cta:'Order the zero bottle' },
      zh:{ name:'青岛啤酒 无醇 330毫升 瓶装',
           tagline:'无醇的口感，装在人们熟悉的那只瓶子里。',
           badge:'0.0% · 330毫升',
           legacy:'不含酒精，却仍是一只地道的啤酒瓶。',
           description:'同一款无醇啤酒，装在熟悉的 330 毫升绿瓶里，而不是易拉罐。风味、酒体与回味完全一致——脱醇技术的应用方式分毫不差，差别只在包装。\n\n对很多人来说，形式本身也是体验的一部分。瓶装的保温比罐装更稳一些，倒起来也更利落，你可以把它放在餐桌上其他瓶子旁边，没有人会问为什么。',
           features:['风味与脱醇工艺与无醇 330 毫升罐装完全相同。',
                     '330 毫升绿瓶：比塑料容器更保温，倒酒也更利落。',
                     '酒精度 0.0%、低热量——与罐装适合同一批人群、同一批场合。'],
           pairing:['家庭聚餐','不必早散的夜晚','与朋友小酌'],
           award:{zh:'与无醇 330 毫升罐装同系列',
                  en:'The same range as the Zero 330 ml can',
                  vi:'Cùng dòng với lon Không Độ 330 ml'},
           cta:'选购无醇瓶装' }
    }
  },

  /* ---------------------------------------------------------------- 7 */
  {
    id:'tsg-lemon-pilsner', slug:'lemon-pilsner', sku:'TSG-LMN-330',
    line:{vi:'Dòng Giải Khát Vị Chanh', en:'The Lemon Refreshment', zh:'柠檬系列'},
    category:'refreshment', order:7, featured:true, ring:'off', ringCaption:'Lemon Pilsner',
    media:{ tile:'097', gallery:['097'] },
    specs:{
      abv:0.0,
      formats:[{kind:'can', volume_ml:330}],
      ingredients:{vi:'Nước, mạch nha lúa mạch, nước cốt chanh tươi, hoa bia, men bia',
                   en:'Water, barley malt, natural lemon juice, hops, yeast',
                   zh:'水、大麦麦芽、鲜榨柠檬汁、啤酒花、酵母'},
      fermentation:null, energy_kcal_100ml:60, sugar_free:false
    },
    copy:{
      vi:{ name:'Bia Chanh Tsingtao 330ml',
           tagline:'Bùng nổ sảng khoái, giải nhiệt tức thì.',
           badge:'CHANH TƯƠI · 60 kcal',
           legacy:'Nước cốt chanh thật, không hương liệu tổng hợp.',
           description:'Một cách giải khát hoàn toàn khác: dòng Pilsner nhạt được pha trộn với nước cốt chanh tươi tự nhiên, đúng tỉ lệ mà một quầy bar tại Đức cũng sẽ pha. Vị chua ngọt cân bằng, sưa sủa mà không chua gắt.\n\nMở lon là thấy hơi ga lấp lánh, mùi chanh bùng lên trước cả khi nếm. Chỉ 60 kcal mỗi 100 ml và không chứa cồn, đây là thức uống của những ngày nắng đổ ngập — hoặc ngay sau buổi tập chạy buổi sáng.',
           features:['Ít calo, không chứa cồn, kết hợp vị chua ngọt tự nhiên dễ uống cho cả nam và nữ.',
                     'Chỉ 60 kcal / 100ml — nhẹ hơn phần lớn nước ngọt cùng loại.',
                     'Thức uống lý tưởng sau các buổi tập luyện thể thao ngoài trời.'],
           pairing:['Sau tập luyện','Ngày hè nắng nóng','Dã ngoại ngoài trời'],
           award:{vi:'Chiết xuất nước cốt chanh tươi tự nhiên',
                  en:'Pressed from natural fresh lemon',
                  zh:'采用天然鲜榨柠檬汁'},
           cta:'Giải nhiệt ngay' },
      en:{ name:'Tsingtao Lemon Pilsner 330ml',
           tagline:'A burst of refreshment that cuts straight through the heat.',
           badge:'REAL LEMON · 60 kcal',
           legacy:'Real pressed lemon. No artificial flavouring.',
           description:'A different kind of refreshment entirely: a light Pilsner base blended with natural fresh lemon juice, in proportions a German bar would recognise. The result is a balanced sweet-sharp finish — bright, never sour.\n\nOpen the can and the sparkle is visible before you even taste it; the lemon lifts first. At just 60 kcal per 100 ml with no alcohol, it is built for the hottest days of the year — or for straight after a morning run.',
           features:['Low in calories and free of alcohol, with a natural sweet-tart balance made for everyone.',
                     'Only 60 kcal / 100ml — lighter than most soft drinks of its kind.',
                     'The natural choice after outdoor training and exercise.'],
           pairing:['After exercise','Hot summer days','Outdoor gatherings'],
           award:{en:'Pressed from natural fresh lemon',
                  vi:'Chiết xuất nước cốt chanh tươi tự nhiên',
                  zh:'采用天然鲜榨柠檬汁'},
           cta:'Cool down instantly' },
      zh:{ name:'青岛啤酒 柠檬皮尔森 330毫升',
           tagline:'清爽爆发，即刻降温。',
           badge:'真柠檬 · 60千卡',
           legacy:'鲜榨柠檬，不含合成香精。',
           description:'一种全然不同的解暑方式：清爽皮尔森与新鲜天然柠檬汁按德式酒吧的经典比例调配。酸甜平衡，明快而不酸涩。\n\n开罐瞬间气泡跃动，柠檬香气先于味觉抵达。每 100 毫升仅 60 千卡且不含酒精，专为酷暑难耐的日子而酿——或晨跑之后的第一口。',
           features:['低卡、不含酒精，天然酸甜平衡，人人皆宜。',
                     '每 100 毫升仅 60 千卡，比同类软饮更轻盈。',
                     '户外运动与锻炼之后的理想饮品。'],
           pairing:['运动之后','炎热夏日','户外聚会'],
           award:{zh:'采用天然鲜榨柠檬汁',
                  en:'Pressed from natural fresh lemon',
                  vi:'Chiết xuất nước cốt chanh tươi tự nhiên'},
           cta:'即刻降温' }
    }
  },

  /* ---------------------------------------------------------------- 8 */
  {
    id:'tsg-lunar-special', slug:'special-edition-2025', sku:'TSG-EDT25-473',
    line:{vi:'Phiên Bản Giới Hạn 2025', en:'Limited 2025 Edition', zh:'2025 限量版'},
    category:'limited', order:8, featured:false, ring:'launch',
    media:{ tile:'089', gallery:['089'] },
    specs:{
      abv:4.7,
      formats:[{kind:'bottle', volume_ml:473}],
      ingredients:{vi:'Nước tinh khiết, mạch nha lúa mạch, hoa bia, men bia',
                   en:'Purified water, barley malt, hops, yeast',
                   zh:'纯净水、大麦麦芽、啤酒花、酵母'},
      fermentation:null, energy_kcal_100ml:null, sugar_free:false, limited:true
    },
    copy:{
      vi:{ name:'Bia Tsingtao Phiên Bản 2025',
           tagline:'Năm Rồng trong một chai trắng — mở ra một năm phúc lộc đầy nhà.',
           badge:'GIỚI HẠN 2025',
           legacy:'Một năm, một con vậy, một mẻ bia riêng.',
           description:'Năm 2025, nhà máy dành riêng một mẻ bia giới hạn cho dịp Tết và trao cho nó một vỏ riêng: thân chai trắng tinh, cổ chai in dòng chữ 2025 SPECIAL EDITION, thân chai vẽ con rồng xanh cuộn lên từ đám mây, và ở dưới cùng là nét thư pháp 福 — chữ Phúc.\n\nBên trong vẫn là Tsingtao Premium Lager với hương vị nguyên bản từ năm 1903. Nhưng khi mở nắp, người nhận không chỉ uống bia — họ mở ra một món quà mang ý nghĩa phong thủy, và có người sẽ giữ lại làm vật trưng bày.',
           features:['Vỏ chai trắng in hoạ tiết riêng cho năm 2025, số lượng có hạn.',
                     'Chất lượng từ mẻ bia giới hạn tinh chọn, dành riêng cho dịp năm mới.',
                     'Sản phẩm dành riêng cho thị trường Việt Nam, không phân phối thường niên.'],
           pairing:['Quà tặng đối tác','Trưng bày trong nhà'],
           award:{vi:'Số lượng giới hạn, chỉ phát hành trong năm',
                  en:'A limited run, released only within the year',
                  zh:'限量发行，仅在当年供应'},
           cta:'Sưu tầm phiên bản 2025' },
      en:{ name:'Tsingtao Special Edition 2025',
           tagline:'The Year of the Dragon in a white bottle — an auspicious year, opened.',
           badge:'LIMITED 2025',
           legacy:'One year, one animal, one brew of its own.',
           description:'For 2025 the brewery set aside a single limited batch for the New Year and gave it a shell to match: a pure white bottle, 2025 SPECIAL EDITION set in type around the neck, a blue dragon curling up from cloud across the body, and at the base the calligraphic character 福 — fortune.\n\nInside is the original Tsingtao Premium Lager, unchanged since 1903. But when the cap comes off, the recipient is not simply opening a beer — they are opening a gift with auspicious meaning, one some will keep rather than drink.',
           features:['A pure white bottle printed for 2025 only, in strictly limited numbers.',
                     'Selected from a single limited brew reserved exclusively for the New Year.',
                     'Produced for the Vietnamese market and not part of the annual range.'],
           pairing:['Corporate gifting','Home display'],
           award:{en:'A limited run, released only within the year',
                  vi:'Số lượng giới hạn, chỉ phát hành trong năm',
                  zh:'限量发行，仅在当年供应'},
           cta:'Collect the 2025 edition' },
      zh:{ name:'青岛啤酒 2025 特别版',
           tagline:'龙年装在一只白瓶里——开瓶即开一个好年。',
           badge:'2025 限量版',
           legacy:'一年，一生肖，一批专属佳酿。',
           description:'2025 年，酒厂为新春单独留出一批限量酒液，并为其配上专属瓶身：通体纯白，瓶颈处印着 2025 SPECIAL EDITION，瓶身绘有一条自云间腾起的蓝色巨龙，底部则是一个行书「福」字。\n\n瓶中仍是 1903 年未曾改变的青岛经典拉格。但当瓶盖旋开，收礼之人开启的不仅是一瓶啤酒，更是一份承载吉祥寓意的礼物——也有人会将它留下珍藏。',
           features:['纯白瓶身，2025 年专属印花，发行数量严格有限。',
                     '限量精选酒液批次，专为新春佳节而酿。',
                     '专为越南市场打造，不属于常规年度产品。'],
           pairing:['商务礼赠','居家陈列'],
           award:{zh:'限量发行，仅在当年供应',
                  en:'A limited run, released only within the year',
                  vi:'Số lượng giới hạn, chỉ phát hành trong năm'},
           cta:'收藏 2025 特别版' }
    }
  },

  /* ---------------------------------------------------------------- 9 */
  {
    id:'tsg-centennial', slug:'centennial-journey', sku:'TSG-CEN-750',
    line:{vi:'Dòng Di Sản Nút Gài', en:'The Heritage Reserve', zh:'典藏系列'},
    category:'reserve', order:9, featured:false, ring:'power',
    media:{ tile:'066', gallery:['066'] },
    specs:{
      abv:5.2,
      formats:[{kind:'swing_top_bottle', volume_ml:750}],
      ingredients:{vi:'Nước tinh khiết, mạch nha lúa mạch, hoa bia, men bia',
                   en:'Purified water, barley malt, hops, yeast',
                   zh:'纯净水、大麦麦芽、啤酒花、酵母'},
      fermentation:null, energy_kcal_100ml:null, sugar_free:false
    },
    copy:{
      vi:{ name:'Bia Di Sản Tsingtao Trăm Năm 750ml',
           tagline:'Chạm tay vào dòng thời gian của một thế kỷ.',
           badge:'NÚT GÀI · 750ml',
           legacy:'Một trăm năm nghệ thuật nấu bia, đóng trong một chai.',
           description:'Cất giữ hình hài một thế kỷ: 750 ml, chai thủy tinh nâu, nắp gài kiểu châu Ân. Chi tiết nhỏ nhưng quyết định — nắp gài tạo áp suất bên trong, giữ lớp bọt mịn và độ tươi ngon như thể chai vừa rời khay chuyển ra khỏi nhà máy.\n\nĐây không phải bia để uống nhanh. Đây là chai để mở chậm, dành cho một dịp đáng nhớ — hoặc để đặt trên kệ quầy bar nhà một người hiểu thứ gì đáng giữ. Vị đậm hơn dòng lager tiêu chuẩn, dành cho người thưởng thức lâu hơn.',
           features:['Thiết kế nắp gài độc bản, tái hiện phong cách thưởng thức bia thượng lưu cổ điển.',
                     'Áp suất nội tại giữ trọn bọt mịn và độ tươi trong thời gian dài.',
                     'Phù hợp làm quà tặng độc đáo hoặc trưng bày trong các không gian quầy bar riêng tư.'],
           pairing:['Món thưởng thức để dành','Trưng bày quầy bar riêng'],
           award:{vi:'Kỷ niệm 100 năm nghệ thuật nấu bia',
                  en:'A centennial of the craft of brewing',
                  zh:'百年酿造工艺纪念之作'},
           cta:'Sở hữu chai di sản' },
      en:{ name:'Tsingtao Centennial Journey 750ml',
           tagline:'A century of brewing craft, held in the hand.',
           badge:'SWING-TOP · 750ml',
           legacy:'A hundred years of brewing craft, sealed in one bottle.',
           description:'A century kept in a bottle: 750 ml, brown crystal, European-style swing-top. The detail is small but decisive — the closure holds pressure inside, preserving the fine head and the live carbonation as though the bottle had only just left the brewery.\n\nThis is not a beer to drink quickly. It is a bottle to open slowly, for an occasion worth marking — or to set on the shelf of someone who understands what is worth keeping. Fuller than the standard lager, and made for the slower drinker.',
           features:['A distinctive swing-top closure that reinstates a classic cellar ritual.',
                     'Internal pressure holds the fine head and freshness over a long period.',
                     'Suited to distinctive gifting, or to display in a private bar setting.'],
           pairing:['A bottle to be savoured','Private bar display'],
           award:{en:'A centennial of the craft of brewing',
                  vi:'Kỷ niệm 100 năm nghệ thuật nấu bia',
                  zh:'百年酿造工艺纪念之作'},
           cta:'Own the heritage bottle' },
      zh:{ name:'青岛啤酒 百年纪念 750毫升',
           tagline:'触手可及的一个世纪酿造工艺。',
           badge:'木塞款 · 750毫升',
           legacy:'一百年的酿造工艺，封印在一只瓶中。',
           description:'用一个世纪的模样装进瓶中：750 毫升，棕色水晶瓶身，欧式木塞封口。细节虽小，却至关重要——木塞在瓶内形成气压，锁住细腻泡沫与鲜活碳酸，仿佛刚刚离开工厂。\n\n这不是用来豪饮的啤酒，而是一只值得慢慢开启的瓶子：为一个值得铭记的时刻而开，或放在一位懂得珍藏之人的私人酒柜上。酒体比标准拉格更饱满，为慢饮者而生。',
           features:['独特木塞设计，重现经典酒窖的品鉴仪式。',
                     '瓶内气压锁住细腻泡沫，长久保持新鲜。',
                     '适合作为别致赠礼，或陈列于私人酒柜。'],
           pairing:['值得慢饮的佳酿','私人酒柜陈列'],
           award:{zh:'百年酿造工艺纪念之作',
                  en:'A centennial of the craft of brewing',
                  vi:'Kỷ niệm 100 năm nghệ thuật nấu bia'},
           cta:'拥有典藏之瓶' }
    }
  },

  /* --------------------------------------------------------------- 10 */
  {
    id:'tsg-seaweed-soda', slug:'seaweed-soda', sku:'TSG-SOD-320',
    line:{vi:'Dòng Nước Khoáng Tảo Biển', en:'The Mineral Soda', zh:'海藻苏打水'},
    category:'soda', order:10, featured:false, ring:'shop',
    media:{ tile:'078', gallery:['078'] },
    specs:{
      abv:0.0,
      formats:[{kind:'slim_can', volume_ml:320}],
      ingredients:{vi:'Nước, chiết xuất tảo biển tự nhiên, khoáng chất thiết yếu, men bia',
                   en:'Water, natural seaweed extract, essential minerals, yeast',
                   zh:'水、天然海藻萃取物、必需矿物质、酵母'},
      fermentation:null, energy_kcal_100ml:0, sugar_free:true, keto:true
    },
    copy:{
      vi:{ name:'Nước Tảo Biển Tsingtao 320ml',
           tagline:'Thanh lọc tự nhiên — sức sống từ đại dương.',
           badge:'KHÔNG ĐƯỜNG',
           legacy:'Từ biển sâu, lên thẳng vào lon.',
           description:'Thức uống soda thế hệ mới, ứng dụng chiết xuất tảo biển tự nhiên kết hợp khoáng chất thiết yếu. Không phải nước ngọt hương vị, và cũng không phải soda thông thường — nó mang vị mặn mòi rất nhẹ của biển, pha cùng độ ga sảng khoái.\n\nDành cho người muốn uống thứ gì đó tươi mới mà vẫn kiểm soát được lượng đường và calo nạp vào. Không đường, không calo, phù hợp với chế độ Keto và bất kỳ ai đang cải thiện lại cách mình ăn uống.',
           features:['Không đường, không calo, phù hợp cho người ăn kiêng (Keto / Healthy).',
                     'Chiết xuất tảo biển tự nhiên, giàu vi khoáng chất — hỗ trợ thanh lọc cơ thể.',
                     'Lon thon gọn 320 ml, vừa tay và vừa túi.'],
           pairing:['Chế độ ăn Keto','Giải khát nhẹ mỗi ngày'],
           award:{vi:'Vị mặn tự nhiên từ khoáng chất biển sâu',
                  en:'A natural saline note from deep-sea minerals',
                  zh:'源自深海矿物质的天然海盐风味'},
           cta:'Thanh lọc tự nhiên' },
      en:{ name:'Tsingtao Seaweed Soda Water 320ml',
           tagline:'Natural clarity — vitality drawn from the ocean.',
           badge:'SUGAR-FREE',
           legacy:'From the deep sea, straight into the can.',
           description:'A next-generation refreshment built on natural seaweed extract and essential minerals. It is neither a flavoured soft drink nor an ordinary soda — it carries the faintest saline note of the sea, lifted by a clean sparkle.\n\nFor anyone who wants something fresh while still keeping sugar and calories under control. Sugar-free, calorie-free, and suited to keto as well as to anyone revising the way they eat.',
           features:['Sugar-free and calorie-free, suited to keto and health-conscious diets.',
                     'Natural seaweed extract, mineral rich, formulated to cleanse the body.',
                     'A slim 320 ml can that fits the hand and the bag.'],
           pairing:['Keto diets','Everyday light refreshment'],
           award:{en:'A natural saline note from deep-sea minerals',
                  vi:'Vị mặn tự nhiên từ khoáng chất biển sâu',
                  zh:'源自深海矿物质的天然海盐风味'},
           cta:'Refresh, naturally' },
      zh:{ name:'青岛啤酒 海藻苏打水 320毫升',
           tagline:'天然净澈，取自海洋的生命力。',
           badge:'无糖',
           legacy:'来自深海，直入罐中。',
           description:'新一代 SODA 饮品，运用天然海藻萃取并结合必需矿物质。它既非调味汽水，也非普通苏打——带着海洋极淡的咸鲜气息，以及清爽干净的气泡。\n\n适合想喝得清新、又想掌控糖分与热量摄入的人。无糖、无热量，适配生酮饮食，也适合每一位正在重新审视自己饮食方式的人。',
           features:['无糖、无热量，适合生酮与健康饮食人群。',
                     '天然海藻萃取，富含矿物质，帮助清洁身体。',
                     '320 毫升细长罐，一手可握，随身好带。'],
           pairing:['生酮饮食','日常轻爽解渴'],
           award:{zh:'源自深海矿物质的天然海盐风味',
                  en:'A natural saline note from deep-sea minerals',
                  vi:'Vị mặn tự nhiên từ khoáng chất biển sâu'},
           cta:'天然净澈' }
    }
  }
  ]
};

/* index by id — the UI addresses products by id, never by array position */
const PRODUCT = {};
CATALOG.products.forEach(function(p){ PRODUCT[p.id] = p; });
const BY_ORDER = CATALOG.products.slice().sort(function(a,b){ return a.order - b.order; });

/* The carousel is a separate concern from the catalogue, but it borrows the
   product captions so a card and a detail page can never disagree. */
const SHOTS = [
  {v:'pay',    u:U('152')},
  {v:'launch', u:U('089'), p:'tsg-lunar-special'},
  {v:'shop',   u:U('078'), p:'tsg-seaweed-soda'},
  {v:'brand',  u:U('105'), p:'tsg-lager-640'},
  {v:'frete',  u:U('167'), p:'tsg-lager-640'},
  {v:'plain',  u:U('052'), p:'tsg-1903-premium'},
  {v:'power',  u:U('066'), p:'tsg-centennial'},
  {v:'plain',  u:U('136'), p:'tsg-zero-bottle'},
  {v:'off',    u:U('097'), p:'tsg-lemon-pilsner'},
  {v:'plain',  u:U('9206'),p:'tsg-lager-500'}
];
/* every product line appears in the store catalogue — not a hand-picked four */
const GOODS = BY_ORDER.map(function(p){ return p.id; });
